name: Build and Promote Docker Image

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'Dockerfile'
      - '.github/workflows/*'

jobs:
  build:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm/v7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Set Docker tag
        id: set_docker_tag
        run: echo "TAG=dev" >> $GITHUB_ENV

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.platform }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.platform }}-

      - name: Build and push to GHCR
        run: |
          docker buildx build --platform ${{ matrix.platform }} \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache,mode=max \
            -t ghcr.io/${{ github.repository_owner }}/fairfruitbot-telegram:${{ env.TAG }} \
            --push .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull and tag from GHCR
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/fairfruitbot-telegram:${{ env.TAG }} \
            --platform ${{ matrix.platform }}
          docker tag ghcr.io/${{ github.repository_owner }}/fairfruitbot-telegram:${{ env.TAG }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/fairfruitbot-telegram:${{ env.TAG }}

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fairfruitbot-telegram:${{ env.TAG }}

  promote:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Set Docker tag
        id: set_docker_tag
        run: echo "TAG=latest" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull and tag from GHCR
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/fairfruitbot-telegram:dev
          docker tag ghcr.io/${{ github.repository_owner }}/fairfruitbot-telegram:dev \
            ${{ secrets.DOCKER_HUB_USERNAME }}/fairfruitbot-telegram:latest

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fairfruitbot-telegram:latest
