name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Set Docker tag
        id: set_docker_tag
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=dev" >> $GITHUB_ENV
          fi

      - name: Build and push to GHCR
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/fairfruitbot-telegram:${{ env.TAG }} .
          docker push ghcr.io/${{ github.repository_owner }}/fairfruitbot-telegram:${{ env.TAG }}

      - name: Pull from GHCR
        run: docker pull ghcr.io/${{ github.repository_owner }}/fairfruitbot-telegram:${{ env.TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and push to Docker Hub
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/fairfruitbot-telegram:${{ env.TAG }} ${{ secrets.DOCKER_HUB_USERNAME }}/fairfruitbot-telegram:${{ env.TAG }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fairfruitbot-telegram:${{ env.TAG }}
