name: Build and Promote Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'Dockerfile'
      - '.github/workflows/*'

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Promote multi-platform image
        run: |
          docker buildx imagetools create ${{ secrets.DOCKER_HUB_USERNAME }}/fairfruitbot-telegram:dev \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/fairfruitbot-telegram:latest
          docker buildx imagetools inspect ${{ secrets.DOCKER_HUB_USERNAME }}/fairfruitbot-telegram:latest
